### ISSUE TITLE
Every request creates 4 tables

### ISSUE THREAD

**Issue by savedario** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#1]
I installed the extension and I am still struggling to make it work.
Whilst investigating, I noticed that 4 new tables with random names get created with every request (Always a certain contact X trying to view/edit contact Y).

Is this how the extension is supposed to work?

**Comment by eileenmcnaughton** [comment]
Yes, they should be TEMPORARY tables so should only be in memory not disk. I haven't revisited this to see if there is a better approach

**Comment by savedario** [comment]
I understand the problem, but mine was caused by the fact that I downloaded master and not the 1.2 branch.
Thanks for answering.
