### ISSUE TITLE
CREATE TABLE generates MySQL error 1171 using MySql 5.7

### ISSUE THREAD

**Issue by rgburton** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#11]

**Comment by rgburton** [comment]
We use this extension in conjunction with webform-civicrm to allow members to select/update existing family members.  Our hosting site recently upgraded MySQL to 5.7 and now this is no longer working.  The logs indicate that the CREATE TEMPORARY TABLE statements fail with MySQL error 1171:

All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

This appears to have changed with MySQL 5.7.3 as indicated in the following change from that release:

Columns in a PRIMARY KEY must be NOT NULL, but if declared explicitly as NULL produced no error. Now an error occurs. For example, a statement such as CREATE TABLE t (i INT NULL PRIMARY KEY) is rejected. The same occurs for similar ALTER TABLE statements. (Bug #13995622, Bug #66987, Bug #15967545, Bug #16545198)

The failing statement is the following:

else {
    $tmpTableName = 'my_relationships_' . $contactID . '_' . rand(10000, 100000);
    $sql = "CREATE TEMPORARY TABLE $tmpTableName (
     `contact_id` INT(10) NULL DEFAULT NULL,
     PRIMARY KEY (`contact_id`)
    )";
    CRM_Core_DAO::executeQuery($sql);

**Comment by eileenmcnaughton** [comment]
It sounds like you are saying this line needs fixing

https://github.com/eileenmcnaughton/nz.co.fuzion.relatedpermissions/blob/master/relatedpermissions.php#L121

Do you have a patch for it?

**Comment by rgburton** [comment]
Actually, I was thinking to change the line

`contact_id` INT(10) NULL DEFAULT NULL

to something like 'contact_id' INT(10) NOT NULL

but I don't know whether that would create other problems.  I haven't had time yet to test something like this.

Richard

**Comment by eileenmcnaughton** [comment]
OK - I'm not going to get to it any time soon but whoever is next in a position to test this hopefully will. I think you have done the hard work - ie the diagnosis
