### ISSUE TITLE
Tag the 1.2 release

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#13]
The c.o page for this extension (https://civicrm.org/extensions/relationship-permissions-acls) says it doesn't work with civi 4.5+, but info.xml says otherwise.  If you tag the new release, I can update the description on c.o for you.

**Comment by eileenmcnaughton** [comment]
Done - although it looks like I skipped it for 1.3
