### ISSUE TITLE
Occasional errors creating myrelationship temporary table

### ISSUE THREAD

**Issue by jackrabbithanna** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#14]
We've been using this extension for a while on one client site, and it has worked well.  This client has organizations which can relate to primary members who can edit the org, and these orgs also get related to other "facility" organizations, which the primary member should be able to edit. This extension made it possible for the primary members to edit the "facility" org data that is related to the main org record....

When we upgraded their site to 4.7.30, we doing our testing, and we get an error:

> DB Error: already exists
> 
> Database Error Code: Table 'myrelationships85500' already exists, 1050

So looking at the code line 97 of relatedpermissions.php
`$tmpTableName = 'myrelationships' . rand(10000, 100000);`

I can see that here occasionally an existing table with a number could exist, and the new table trying to be created could have the same number. 

My question is this: how long should these tables exist for?
Does it hurt to flush them out occasionally? 
If we do drop them, will new ones be created, and does this really harm the user experience in any way?

Also I'm thinking about just adding some code that checks if the table exists before it tries to create it, and come up with a better way to get a random number/hash...

But I want to do if dropping all the existing tables will "hurt".

**Comment by eileenmcnaughton** [comment]
These tables should really be purged quite frequently. I don't think they way they were intended to be re-used ever worked very well.... they will re-spawn

**Comment by jackrabbithanna** [comment]
Ok thanks for the feedback Eileen :)  I can setup a cron job to take care of that.

**Comment by axon-obriend** [comment]
I've got a GAZILLION tables -- OK, not a GAZILLION, but a lot -- 3117 each of 'myrelationships%' and 'mysecondaryrelationps%'

Based on the answer here, it seems like they're OK to delete. I can get rid of them. If @jackrabbithannah doesn't mind sharing his cron job, so much the better.

**Comment by jackrabbithanna** [comment]
So I created a custom API action on the relationship entity.

What you can do is add a api/v3/Relationship directory structure to this extension...
then I put a file called PruneTempTables.php in the Relationship directory

lil code:
```

/**
 * Relationship.PruneTempTables API specification (optional)
 * This is used for documentation and validation.
 *
 * @param array $spec description of fields supported by this API call
 * @return void
 * @see http://wiki.civicrm.org/confluence/display/CRM/API+Architecture+Standards
 */
function _civicrm_api3_relationship_prune_temp_tables_spec(&$spec) {
  $spec['magicword']['api.required'] = 0;
}

/**
 * Relationship.PruneTempTables API
 *
 * @param array $params
 * @return array API result descriptor
 * @see civicrm_api3_create_success()
 * @see civicrm_api3_create_error()
 * @throws API_Exception
 */
function civicrm_api3_relationship_prune_temp_tables($params) {
  try {
    $dao = CRM_Core_DAO::executeQuery(
      "SELECT TABLE_NAME
       FROM information_schema.TABLES
       WHERE TABLE_SCHEMA = '" . CRM_Core_DAO::getDatabaseName() . "'
     ");

    while ($dao->fetch()) {
      $tables[] = $dao->TABLE_NAME;
    }
    $dao->free();
    if (!empty($tables)) {
      foreach ($tables as $table_name) {
        if (strpos($table_name, 'myrelationships') === 0 || strpos($table_name, 'mysecondaryrelationships') === 0) {
          $dao = CRM_Core_DAO::executeQuery("DROP TABLE IF EXISTS $table_name");
        }
      }
    }
    $return_values = array('status' => 'success');
    return civicrm_api3_create_success($return_values, $params, 'Relationship', 'rp_prune_temp_tables');
  }
  catch (Exception $e) {
    throw new API_Exception('Error clearing temp tables.');
  }
}
```

Then I added a scheduled job
here: "civicrm/admin/job?reset=1"
and gave it the settings:
Name: Drop temporary relationship ACL tables
Run frequency: Daily
API Call: Relationship , prune_temp_tables
set it to be active

**Comment by jackrabbithanna** [comment]
@eileenmcnaughton if you like that I can make a PR for this extension

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna sounds good to me!

**Comment by jackrabbithanna** [comment]
https://github.com/eileenmcnaughton/nz.co.fuzion.relatedpermissions/pull/15

**Comment by eileenmcnaughton** [comment]
Should we close this or will you add an .mgd.php file for the job?

**Comment by jackrabbithanna** [comment]
never added one of those before, I been making the scheduled jobs manually...guess I've been missing out on a step....where's a good one I can copy from?

**Comment by eileenmcnaughton** [comment]
https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/blob/master/api/v3/Job/ProcessRecurring.mgd.php

**Comment by mattwire** [comment]
@jackrabbithanna Just a quick ping to see if you have time to create a PR with an mgd file?

**Comment by jackrabbithanna** [comment]
I can do it, it may be a few days until I can focus on that though.
