### ISSUE TITLE
Any plans....

### ISSUE THREAD

**Issue by com2** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#2]
... to upgrade this for 4.6.x? Is there any way to influence this by way of donations?

**Comment by eileenmcnaughton** [comment]
I would certainly move it up my to-do list :-)

**Comment by yosefromano** [comment]
happy to contribute as well.
It looks like it works on 4.6 already but I do get an error when trying to create new relationships. The only way I can create new relationships is through drupal webforms.

**Comment by eileenmcnaughton** [comment]
I'm pretty sure we have this running on several 4.6 sites now - you do need to install the entity setting extension (manually) and  make sure you do things like turning logging off & on (if you have logging) afterwards and clearing caches

Entity settings extension is here 
https://github.com/eileenmcnaughton/nz.co.fuzion.entitysetting

NB - any contributions are best directed to the main CiviCRM contribution page at this stage
https://civicrm.org/civicrm/contribute/transact?reset=1&id=47

**Comment by colemanw** [comment]
@eileenmcnaughton this issue can be closed, 4.6 & 4.7 have been added to the xml.
