### ISSUE TITLE
Error when trying to install this extension in CiviCRM 4.6

### ISSUE THREAD

**Issue by cristina-p** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#23]
Good morning,

I'm trying to install this extension in CiviCRM 4.6.31 and I get this error:

Fatal error: Call to undefined method CRM_Core_SelectValues::getPermissionedRelationshipOptions() in C:\Apache24\htdocs\drupal\sites\default\files\civicrm\custom_ext\nz.co.fuzion.relatedpermissions-1.5\CRM\Relatedpermissions\Upgrader.php on line 52

In the github repository I can only see 1.5 and 1.6 releases which are compatible with CiviCRM 5.5 and 5.6 respectively.

Could you please give me a hand with this?
It would be really appreciated!

**Comment by aydun** [comment]
Hi, sorry but the extension uses functions only found in newer versions of CiviCRM so is not compatible with 4.6.  Please upgrade to the current version of Civi.
