### ISSUE TITLE
error when trying to install in CiviCRM 5.13

### ISSUE THREAD

**Issue by lbl-knts** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#25]
I am trying to get the extension to work in CiviCRM 5.13, but its the same error during install in two different installations:`'Integer' is not a valid option for field data_type`, which should be a valid option, i guess. 
It is located in the `upgrader.php` on Line 50. I have tried a couple of different expressions like `integer` or `INTEGER` with no other results. 
Any ideas or hints?

thanks!

**Comment by yasarts** [comment]
Same here.

**Comment by eileenmcnaughton** [comment]
I just changed them to 'Int' which is working for me in other extensions
