### ISSUE TITLE
Related permissions settings defaults not applying

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#28]
When we try and add a relationship (manually), once we select a relationship type none of the defaults / overrides apply. They just stay at none. We are on WP 5.3, Civi 5.17.5 and have eliminated as many causes as possible.

We have disabled all Civi extensions except for this one (nz.co.fuzion.relatedpermissions) and disabled all WP plugins except for CiviCRM of course. We are running 2017 WP theme. We have no custom template directory. So we are left with a stripped down Civi.

We saw this behavior when we were testing on our staging. We then decided to try it out on production and the defaults /  overrides did apply. Now it has stopped working again, which makes this very strange that it once worked. This is a multisite.

So it looks like this JS file is not getting applied https://github.com/eileenmcnaughton/nz.co.fuzion.relatedpermissions/blob/master/js/set_permissions.js.

Do you have suggestions on debugging further? Has this occurred before?

**Comment by andyburnsco** [comment]
It works for 2 relationships out of 7 which have these settings. Quite bizarre. I tried deleting a row in civicrm_value_related_permi and then re-setting permissions for a relationship.  When I add a new relationship it is the exact same as the ones that work in terms of what contact types it relates to. Just the name is the difference. No success.

**Comment by andyburnsco** [comment]
Resolved.

I rebuilt the triggers and deleted the data in civicrm_value_related_permi. Then uninstalled and reinstalled.

**Comment by eileenmcnaughton** [comment]
Glad you got there with it

**Comment by andyburnsco** [comment]
So I figured out the root cause. The defaults work if I have 5 or less rows in the civicrm_value_related_permi_ table. If I exceed that, they are stop working. Help?

**Comment by andyburnsco** [comment]
So I figured out the root cause. The defaults work if I have 5 or less rows in the civicrm_value_related_permi_ table. If I exceed that, they all stop working. Help?

**Comment by eileenmcnaughton** [comment]
I see there was a patch that might help with this in master so I added a release (1.8) so it would be in the released version
