### ISSUE TITLE
incorrectly sets default values on existing relationships

### ISSUE THREAD

**Issue by lcdservices** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#35]
We ran into the following issue:

- contact exists and has an employer relationship where view/update is selected in both directions
- related permission extension installed an "none" is set as the default for both directions, for the employer rel type
- event registration form is created and the profile includes the current employer field is included
- user completes the registration form. the view/update permissions are lost

The problem is that the related permission extension triggers on the pre hook, and assumes all existing values are included in the parameters. That's not a safe assumption. When the relationship is created via the event registration profile, the existing permission values are not included, and so the default values are getting set -- overriding the existing values.

**Comment by lcdservices** [comment]
here's PR  for consideration:
https://github.com/eileenmcnaughton/nz.co.fuzion.relatedpermissions/pull/36

I considered pulling existing values and doing a comparison, but I actually think that we should only ever set the default value when creating a relationship. Any time we're editing a relationship, we should retain whatever existing values are set. That's what this PR does.

**Comment by agileware-justin** [comment]
@lcdservices Good catch Brian :)

**Comment by alexmarketaccess** [comment]
I see this issue is still tagged as open. Brian resolved this issue for us, but I'm wondering if his PR has been integrated into the latest release -- 1.9?

**Comment by agileware-justin** [comment]
Good question @alexmarketaccess

**Comment by agileware-justin** [comment]
@eileenmcnaughton can you please tag a new release which includes this fix 1.9.2?

**Comment by eileenmcnaughton** [comment]
OK - tagged
