### ISSUE TITLE
"Always permission" doesn't work on relations assigned by case [CiviCRM 4.6.8]

### ISSUE THREAD

**Issue by michalet** [eileenmcnaughton/nz.co.fuzion.relatedpermissions#5]
Goal: Case manager can edit clients' contact details (relationship: Case Coordinator)

The "always permission" option works when relationships are assigned manually, but not when it's done by CiviCRM itself as the Case Coordinator when a new CiviCase case is created. Simply saving the relationship without any change fixes this, but "resaving" for each new case is far from the ideal state.

**Comment by eileenmcnaughton** [comment]
This is actually a CiviCRM core bug rather than a bug in the extension - the core code is by-passing the hook

**Comment by michalet** [comment]
Oh, no way to bypass the bypass then, I guess?

I'll have to check if I can achieve the goal with smart groups and ACL. Will be more work, but should work.

**Comment by eileenmcnaughton** [comment]
You might be able to log a bug in core - you would need to explain exactly what path by-passes the hook

**Comment by michalet** [comment]
I'll surely try, but have to ask what do you mean by "explain exactly what path by-passes the hook"? I'm not sure what you mean with "what path" - sorry, I'm not a dev and English is not my mother tongue.

**Comment by eileenmcnaughton** [comment]
I guess I mean that path through the code. Basically the internal CiviCRM code _should_ give the extension a chance to intervene when saving a relationship but that doesn't seem to be happening in this case. However, to log a CiviCRM core bug you need to explain the steps you do on the UI - what page you navigate to & what steps you take.

**Comment by michalet** [comment]
Ok, [created the issue](https://issues.civicrm.org/jira/browse/CRM-17349). Hope I didn't forget any important info there.

Thanks a lot for your help.

**Comment by eileenmcnaughton** [comment]
closing as 4.6 no longer supported
